---
title: "240A Homework 2"
author: "Riley Latham"
date: "January 25, 2022"
output: ioslides_presentation
---

```{r setup, include=FALSE}

#knitr::opts_chunk$set(echo = FALSE)
#knitr::opts_chunk$set(prompt = TRUE)
#hook1 <- function(x){ gsub("```\n*```r*\n*", "", x) }
# These lines improve formatting of output by removing blank space
hook2 <- function(x){ gsub("```\n+```\n", "", x) }
knitr::knit_hooks$set(document = hook2)
```

```{r Gather Libraries, echo=F, results=F}
library(tidyverse, dplyr, sandwich)

library(lmtest)

set.seed(42)
```

## 1

We first create our data matrix with each moment populating its own column.

```{r}
set.seed(42)

# Create list of distributions of interest
dist_list = list(N01 = function(n) rlnorm(n,0,1),
                 N31 = function(n) rlnorm(n,3,1),
                 N03 = function(n) rlnorm(n,0,3))

# Create simulation function to generate results.
sim_func = function(rep, n, pop_dist){
  
  dat <- tibble(xx = dist_list[[pop_dist]](n),
           err = rnorm(n=n,0,1),
           y=xx+err)
  reg <- lm(y~xx, data=dat)
  results <- list(beta_lm = coefficients(reg)[2], beta_ana = cov(x=dat$xx, y=dat$y)/var(x=dat$xx))
  return(results)
}

# Instantiate repetitions and grid of parameters for running simulations
num_reps=1000
param_list <- expand.grid(rep=1:num_reps, n=c(10,100,1000), pop_dist = c("N01", "N31", "N03")) 

# Pass parameters to simulation
sim_out <- param_list %>%
  mutate(results=pmap(param_list,sim_func)) %>%
  unnest_wider(results) 

# Group and print relevant information
sim_print <- group_by(sim_out,n,pop_dist) %>%
  mutate(mean_beta=mean( beta_lm)) %>%
  ungroup() %>%
  select(n,pop_dist,mean_beta) %>%
  distinct() %>%
  pivot_wider(names_from=pop_dist, values_from=mean_beta)

sim_print

```

## 2

Let's first create our data set and instantiate the proper variables.

```{r}

# takes in an amount of values to replace labeled index and a starting list, in this case a vector of 100 zeros.
# recursively applies the replace function to get our new list of sparse dummy variables.
replace_func = function(index, n) {
  for (i in 1:index) {
  n = replace(n, i, 1)
  }
  return(n)
}
```

Now we can simulate these regressions under different HCx situations.

```{r}
set.seed(42)

# First we build our regression function

reg_test = function(rep, omega, index, covtype){
  # Instantiate vector of zeros 
  n = rep(0,100)
  n = replace_func(index, n) # Use the replace function to build the dummy vector
  p = length(which(n==1))
  errors = c(rnorm(p, 0, omega^2), rnorm(length(n)-p, 0, 1)) # Build error vector based on inputs omega and index
  
  df = tibble(xx = n, # Dummy variables for data generation are repressed by beta = 0
              err = errors,
              y = err**2)
  
  reg = lm(y~xx, data=df)
  
  AVSE = sqrt(diag(vcovHC(reg, type=covtype)))[2] # average Squared variance estimate
  
  return(list(True = diag(vcovHC(reg, type=covtype))[2], AvgOver = AVSE, 
              T_stat = coeftest(reg, vcov. = vcovHC(reg, type = 'HC1'))[6]))
}

## Parameter Settings
param_list.2 <- expand.grid(rep=1:100, omega = c(1,2), index=c(3,10,25), covtype=list("const", "HC0", "HC1", "HC2"))

## Run simulation
sim_out.2 <- param_list.2 %>%
  mutate(results=pmap(param_list.2,reg_test)) %>%
  unnest_wider(results)

# Print for True
sim_print.true <- group_by(sim_out.2, omega, index, covtype) %>%
  mutate(mean_beta=mean(True)) %>%
  ungroup() %>%
  select(omega,index,covtype,mean_beta) %>%
  distinct() %>%
  pivot_wider(names_from=covtype, values_from=mean_beta)

sim_print.true

# Print for AVSE
sim_print.avse <- group_by(sim_out.2, omega, index, covtype) %>%
  mutate(mean_beta=mean(AvgOver)) %>%
  ungroup() %>%
  select(omega,index,covtype,mean_beta) %>%
  distinct() %>%
  pivot_wider(names_from=covtype, values_from=mean_beta)

sim_print.avse

# Print for T-Test
sim_print.ttest <- group_by(sim_out.2, omega, index, covtype) %>%
  mutate(mean_beta=mean(T_stat)) %>%
  ungroup() %>%
  select(omega,index,covtype,mean_beta) %>%
  distinct() %>%
  pivot_wider(names_from=covtype, values_from=mean_beta)

sim_print.ttest

```

